# Generated by Django 4.1.2 on 2022-10-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha1', models.CharField(max_length=255)),
                ('linha2', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=25)),
                ('pais', models.CharField(max_length=25)),
                ('latitude', models.IntegerField(blank=True, null=True)),
                ('lontitude', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
